export { ReactComponent as IconCross } from "./cross.svg";
export { ReactComponent as IconExternal } from "./external.svg";
export { ReactComponent as IconFolderAdd } from "./folder-add.svg";
export { ReactComponent as IconFolder } from "./folder.svg";
export { ReactComponent as IconHome } from "./home.svg";
export { ReactComponent as IconLsLabeling } from "./ls-labeling.svg";
export { ReactComponent as IconLsReview } from "./ls-review.svg";
export { ReactComponent as IconUserAdd } from "./user-add.svg";
export { ReactComponent as IconHumanSignal } from "./humansignal.svg";
